criação do esqueleto de matricula
pauloborba/teaching-assistant pull request #8
Opened 2020-11-12 20:06 UTC by hopperjc

2020-11-13 00:42 UTC, pauloborba requested changes

2020-11-13 00:42 UTC, pauloborba commented on ta-server/spec/support/matricula.ts
> +    avaliacoesList: Avaliacoes[] = []
@hopperjc usa os nomes que estão no DDD. não existe Avaliações, mas sim Avaliação. também nao existe Roteiros, AutoAvaliacoes, nem Monitor

2020-11-13 01:19 UTC, pauloborba requested changes

2020-11-13 01:19 UTC, pauloborba commented on ta-server/spec/support/matricula.ts
> +    respostaDeRoteiro: respostaDeRoteiro[] = []
o atributo deve estar no plural, já que ele representa várias (um array) respostas

2020-11-13 01:19 UTC, pauloborba commented on ta-server/spec/support/matricula.ts
>      autoAvaliacao: AutoAvaliacao[] = []
não existe a classe AutoAvaliacao @hopperjc!

2020-11-13 17:11 UTC, pauloborba requested changes

2020-11-13 17:11 UTC, pauloborba commented on ta-server/spec/support/matricula.ts
> +    autoAvaliacao: AutoAvaliacoes[] = []
continua com problema @hopperjc

2020-11-14 19:37 UTC, pauloborba requested changes

2020-11-14 19:37 UTC, pauloborba commented on ta-server/spec/support/matricula.ts
> +    respostaDeRoteiro: respostaDeRoteiro
@hopperjc tem várias respostas. isso é o que indica o * no modelo.

2020-11-14 19:37 UTC, pauloborba commented on ta-server/spec/support/matricula.ts
> +    respostaDeRoteiro: respostaDeRoteiro
no modelo não existe as classes Avaliacoes e AutoAvaliacoes

2020-11-14 20:40 UTC, hopperjc commented
Professor, no modelo tem avaliação que engloba autoavaliações e avaliações.
Gostaria de saber como representar isso no código já q não estou
conseguindo acertar

Em sáb., 14 de nov. de 2020 às 16:37, Paulo Borba <notifications@github.com>
escreveu:

> *@pauloborba* requested changes on this pull request.
> ------------------------------
>
> In ta-server/spec/support/matricula.ts
> <https://github.com/pauloborba/teaching-assistant/pull/8#discussion_r523454795>
> :
>
> > @@ -1,13 +1,13 @@
>
>  export class Matricula{
>
>      aluno: Aluno
>
> -    avaliacao: Avaliacoes[] = []
>
> -    autoAvaliacao: AutoAvaliacoes[] = []
>
> -    monitor: Monitor
>
> -    respostaDeRoteiro: respostasDeRoteiros[] = []
>
> +    avaliacoes: Avaliacoes[] = []
>
> +    autoAvaliacoes: AutoAvaliacoes[] = []
>
> +    monitor: Monitor
>
> +    respostaDeRoteiro: respostaDeRoteiro
>
>
> @hopperjc <https://github.com/hopperjc> tem várias respostas. isso é o
> que indica o * no modelo.
> ------------------------------
>
> In ta-server/spec/support/matricula.ts
> <https://github.com/pauloborba/teaching-assistant/pull/8#discussion_r523454906>
> :
>
> > @@ -1,13 +1,13 @@
>
>  export class Matricula{
>
>      aluno: Aluno
>
> -    avaliacao: Avaliacoes[] = []
>
> -    autoAvaliacao: AutoAvaliacoes[] = []
>
> -    monitor: Monitor
>
> -    respostaDeRoteiro: respostasDeRoteiros[] = []
>
> +    avaliacoes: Avaliacoes[] = []
>
> +    autoAvaliacoes: AutoAvaliacoes[] = []
>
> +    monitor: Monitor
>
> +    respostaDeRoteiro: respostaDeRoteiro
>
>
> no modelo não existe as classes Avaliacoes e AutoAvaliacoes
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pauloborba/teaching-assistant/pull/8#pullrequestreview-530599796>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHBXWUIBJZ3EC5DZI6YLDSDSP3MALANCNFSM4TTXI7JA>
> .
>

2020-11-14 20:45 UTC, pauloborba commented
autoavaliações e avaliações são atributos de Matrícula, não classes.

Assim, por exemplo, tem que definir o atributo autoavaliações com tipo
array de Avaliação

On Sat, Nov 14, 2020, 5:40 PM matheus hopper <notifications@github.com>
wrote:

> Professor, no modelo tem avaliação que engloba autoavaliações e avaliações.
> Gostaria de saber como representar isso no código já q não estou
> conseguindo acertar
>
> Em sáb., 14 de nov. de 2020 às 16:37, Paulo Borba <
> notifications@github.com>
> escreveu:
>
> > *@pauloborba* requested changes on this pull request.
> > ------------------------------
> >
> > In ta-server/spec/support/matricula.ts
> > <
> https://github.com/pauloborba/teaching-assistant/pull/8#discussion_r523454795
> >
> > :
> >
> > > @@ -1,13 +1,13 @@
> >
> > export class Matricula{
> >
> > aluno: Aluno
> >
> > - avaliacao: Avaliacoes[] = []
> >
> > - autoAvaliacao: AutoAvaliacoes[] = []
> >
> > - monitor: Monitor
> >
> > - respostaDeRoteiro: respostasDeRoteiros[] = []
> >
> > + avaliacoes: Avaliacoes[] = []
> >
> > + autoAvaliacoes: AutoAvaliacoes[] = []
> >
> > + monitor: Monitor
> >
> > + respostaDeRoteiro: respostaDeRoteiro
> >
> >
> > @hopperjc <https://github.com/hopperjc> tem várias respostas. isso é o
> > que indica o * no modelo.
> > ------------------------------
> >
> > In ta-server/spec/support/matricula.ts
> > <
> https://github.com/pauloborba/teaching-assistant/pull/8#discussion_r523454906
> >
> > :
> >
> > > @@ -1,13 +1,13 @@
> >
> > export class Matricula{
> >
> > aluno: Aluno
> >
> > - avaliacao: Avaliacoes[] = []
> >
> > - autoAvaliacao: AutoAvaliacoes[] = []
> >
> > - monitor: Monitor
> >
> > - respostaDeRoteiro: respostasDeRoteiros[] = []
> >
> > + avaliacoes: Avaliacoes[] = []
> >
> > + autoAvaliacoes: AutoAvaliacoes[] = []
> >
> > + monitor: Monitor
> >
> > + respostaDeRoteiro: respostaDeRoteiro
> >
> >
> > no modelo não existe as classes Avaliacoes e AutoAvaliacoes
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/pauloborba/teaching-assistant/pull/8#pullrequestreview-530599796
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AHBXWUIBJZ3EC5DZI6YLDSDSP3MALANCNFSM4TTXI7JA
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pauloborba/teaching-assistant/pull/8#issuecomment-727262452>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJGYJF375NCWZWPJN3RIJTSP3TMFANCNFSM4TTXI7JA>
> .
>

2020-11-15 13:07 UTC, pauloborba requested changes

2020-11-15 13:07 UTC, pauloborba commented on ta-server/spec/support/matricula.ts
> +    getRespostasDeRoteiros(): RespostaDeRoteiro;
@hopperjc falta [] no tipo de retorno

2020-11-15 21:41 UTC, merged